export const PL = {
  appName: 'Don Papa Match Play',
  nav: {
    groups: 'Grupy',
    players: 'Zawodnicy',
    playoff: 'Play-off',
    news: 'Aktualności',
    rules: 'Regulamin',
    hallOfFame: 'Galeria Sław',
    previousSeasons: 'Poprzednie Sezony',
    admin: 'Admin',
    login: 'Zaloguj się',
    logout: 'Wyloguj',
    dashboard: 'Dashboard',
    managePlayers: 'Zawodnicy',
    manageAdmins: 'Administratorzy',
    manageSeason: 'Sezon',
    generateRounds: 'Generuj rundy',
    managePlayoff: 'Play-off',
  },
  standings: {
    position: '#',
    player: 'Zawodnik',
    played: 'R',
    won: 'W',
    drawn: 'Rem',
    lost: 'P',
    bigPoints: 'Pkt',
    smallPoints: 'M.pkt',
    hcp: 'HCP',
  },
  match: {
    vs: 'vs',
    unplayed: 'Do rozegrania',
    result: 'Wynik',
    enterResult: 'Wprowadź wynik',
    editResult: 'Edytuj wynik',
    winner: 'Zwycięzca',
    draw: 'Remis',
    walkover: 'Walkower',
    save: 'Zapisz',
    cancel: 'Anuluj',
    preview: 'Podgląd punktów',
  },
  player: {
    firstName: 'Imię',
    lastName: 'Nazwisko',
    email: 'Email',
    phone: 'Telefon',
    hcp: 'Handicap',
    upcomingMatches: 'Mecze do rozegrania',
    matchHistory: 'Historia meczów',
    noUpcoming: 'Brak meczów do rozegrania',
    noHistory: 'Brak rozegranych meczów',
    addPlayer: 'Dodaj zawodnika',
    editPlayer: 'Edytuj zawodnika',
  },
  group: {
    standings: 'Tabela',
    matches: 'Mecze',
  },
  admin: {
    addAdmin: 'Dodaj administratora',
    email: 'Email',
    password: 'Hasło',
    confirmDelete: 'Czy na pewno chcesz usunąć?',
  },
  season: {
    createSeason: 'Utwórz sezon',
    name: 'Nazwa',
    year: 'Rok',
  },
  round: {
    generate: 'Generuj grupy',
    approve: 'Zatwierdź',
    preview: 'Podgląd grup',
  },
  playoff: {
    title: 'Play-off',
    bracket: 'Drabinka',
    bracket116: 'Drabinka 1-16',
    bracket1732: 'Drabinka 17-32',
    bracket3348: 'Drabinka 33-48',
    holes18: '18 dołków',
    holes9: '9 dołków',
    holes918: '9/18 dołków',
    roundOf16: '1/8 Finału',
    quarterFinal: 'Ćwierćfinał',
    semiFinal: 'Półfinał',
    final: 'Finał',
    champion: 'Zwycięzca',
    tbd: 'Oczekuje na wynik',
    deadline: 'do',
    createPlayoff: 'Utwórz drabinki play-off',
    seedingPreview: 'Podgląd rozstawienia',
    confirmCreate: 'Zatwierdź i utwórz mecze',
    globalRanking: 'Ranking końcowy fazy grupowej',
    noPlayoff: 'Play-off nie został jeszcze utworzony.',
    playoffExists: 'Play-off już istnieje.',
    bye: 'BYE',
  },
  reminders: {
    send: 'Wyślij przypomnienia',
    sending: 'Wysyłanie...',
    sent: 'Wysłano',
    emailsSent: 'emaili wysłanych',
    noReminders: 'Brak przypomnień do wysłania (terminy nie wypadają za 7 lub 2 dni)',
    errors: 'błędów',
  },
  playerAuth: {
    loginWithPassword: 'Zaloguj hasłem',
    loginWithMagicLink: 'Zaloguj linkiem',
    email: 'Email',
    password: 'Hasło',
    login: 'Zaloguj',
    setPassword: 'Ustaw hasło',
    changePassword: 'Zmień hasło',
    newPassword: 'Nowe hasło',
    passwordMinLength: 'Minimum 6 znaków',
    passwordSet: 'Hasło zostało ustawione',
    invalidCredentials: 'Nieprawidłowy email lub hasło',
  },
  scoring: {
    config: 'Konfiguracja punktacji',
    bigPoints: 'Punktacja g\u0142\u00f3wna',
    smallPoints: 'Ma\u0142e punkty',
    win: 'Wygrana',
    draw: 'Remis',
    loss: 'Pora\u017cka',
    unplayed: 'Nierozegrany',
    walkoverWinner: 'Walkower (zwyci\u0119zca)',
    walkoverLoser: 'Walkower (przegrany)',
    winnerPoints: 'Wygrany',
    loserPoints: 'Przegrany',
    resultCode: 'Wynik',
    save: 'Zapisz konfiguracj\u0119',
    resetDefaults: 'Przywr\u00f3\u0107 domy\u015blne',
    saved: 'Konfiguracja zapisana',
  },
  simulation: {
    title: 'Symulacja sezonu',
    warning: 'UWAGA: Symulacja nadpisuje istniejące dane. Używaj tylko do testowania!',
    simulateCurrentRound: 'Symuluj bieżącą rundę',
    simulateToPlayoff: 'Symuluj do play-off',
    simulateFullSeason: 'Symuluj cały sezon',
    resetSimulation: 'Reset symulacji',
    confirmReset: 'Czy na pewno chcesz zresetować symulację? To usunie wszystkie wyniki i rundy 2+.',
    running: 'Symulacja w toku...',
    completed: 'Symulacja zakończona',
    matchesSimulated: 'meczów zasymulowanych',
    roundsCreated: 'rund utworzonych',
    resetCompleted: 'Reset zakończony. Runda 1 przywrócona do stanu początkowego.',
  },
  hallOfFame: {
    title: 'Galeria Sław',
    subtitle: 'Zwycięzcy kolejnych sezonów ligi Don Papa Match Play',
    noData: 'Galeria sław będzie wkrótce uzupełniona',
    noDataHint: 'Tu pojawią się zdjęcia i dane zwycięzców kolejnych sezonów.',
    photoSoon: 'Zdjęcie wkrótce',
    season: 'Sezon',
  },
  schedule: {
    title: 'Nadchodzące mecze',
    selectDate: 'Umów termin',
    changeDate: 'Zmień termin',
    scheduled: 'Termin',
    noScheduled: 'Brak zaplanowanych meczów',
    saved: 'Termin zapisany',
    cleared: 'Termin usunięty',
    clear: 'Usuń termin',
    matches: 'meczów',
  },
  previousSeasons: {
    title: 'Poprzednie Sezony',
    subtitle: 'Archiwum wyników z poprzednich sezonów',
    finalStandings: 'Klasyfikacja końcowa',
    matchResults: 'Wyniki meczów',
    gallery: 'Galeria zdjęć',
    photos: 'Zdjęcia',
    viewResults: 'Zobacz wyniki',
    noPhotos: 'Brak zdjęć z tego sezonu',
    noCompletedSeasons: 'Brak zakończonych sezonów',
    rounds: 'rundy',
    players: 'zawodników',
  },
  sponsors: {
    title: 'Partnerzy',
  },
  common: {
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    add: 'Dodaj',
    search: 'Szukaj...',
    loading: 'Ładowanie...',
    noData: 'Brak danych',
    back: 'Wróć',
    close: 'Zamknij',
    allPlayers: 'Wszyscy zawodnicy',
  },
} as const
