export const PL = {
  appName: 'Don Papa Match Play',
  nav: {
    groups: 'Grupy',
    players: 'Zawodnicy',
    admin: 'Panel admina',
    login: 'Zaloguj się',
    logout: 'Wyloguj',
    dashboard: 'Dashboard',
    managePlayers: 'Zawodnicy',
    manageAdmins: 'Administratorzy',
    manageSeason: 'Sezon',
    generateRounds: 'Generuj rundy',
  },
  standings: {
    position: '#',
    player: 'Zawodnik',
    played: 'R',
    won: 'W',
    drawn: 'Rem',
    lost: 'P',
    bigPoints: 'Pkt',
    smallPoints: 'M.pkt',
    hcp: 'HCP',
  },
  match: {
    vs: 'vs',
    unplayed: 'Do rozegrania',
    result: 'Wynik',
    enterResult: 'Wprowadź wynik',
    editResult: 'Edytuj wynik',
    winner: 'Zwycięzca',
    draw: 'Remis',
    walkover: 'Walkower',
    save: 'Zapisz',
    cancel: 'Anuluj',
    preview: 'Podgląd punktów',
  },
  player: {
    firstName: 'Imię',
    lastName: 'Nazwisko',
    email: 'Email',
    phone: 'Telefon',
    hcp: 'Handicap',
    upcomingMatches: 'Mecze do rozegrania',
    matchHistory: 'Historia meczów',
    noUpcoming: 'Brak meczów do rozegrania',
    noHistory: 'Brak rozegranych meczów',
    addPlayer: 'Dodaj zawodnika',
    editPlayer: 'Edytuj zawodnika',
  },
  group: {
    standings: 'Tabela',
    matches: 'Mecze',
  },
  admin: {
    addAdmin: 'Dodaj administratora',
    email: 'Email',
    password: 'Hasło',
    confirmDelete: 'Czy na pewno chcesz usunąć?',
  },
  season: {
    createSeason: 'Utwórz sezon',
    name: 'Nazwa',
    year: 'Rok',
  },
  round: {
    generate: 'Generuj grupy',
    approve: 'Zatwierdź',
    preview: 'Podgląd grup',
  },
  common: {
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    add: 'Dodaj',
    search: 'Szukaj...',
    loading: 'Ładowanie...',
    noData: 'Brak danych',
    back: 'Wróć',
  },
} as const
