export const PL = {
  appName: 'Don Papa Match Play',
  nav: {
    groups: 'Grupy',
    players: 'Zawodnicy',
    playoff: 'Play-off',
    news: 'Aktualności',
    admin: 'Admin',
    login: 'Zaloguj się',
    logout: 'Wyloguj',
    dashboard: 'Dashboard',
    managePlayers: 'Zawodnicy',
    manageAdmins: 'Administratorzy',
    manageSeason: 'Sezon',
    generateRounds: 'Generuj rundy',
    managePlayoff: 'Play-off',
  },
  standings: {
    position: '#',
    player: 'Zawodnik',
    played: 'R',
    won: 'W',
    drawn: 'Rem',
    lost: 'P',
    bigPoints: 'Pkt',
    smallPoints: 'M.pkt',
    hcp: 'HCP',
  },
  match: {
    vs: 'vs',
    unplayed: 'Do rozegrania',
    result: 'Wynik',
    enterResult: 'Wprowadź wynik',
    editResult: 'Edytuj wynik',
    winner: 'Zwycięzca',
    draw: 'Remis',
    walkover: 'Walkower',
    save: 'Zapisz',
    cancel: 'Anuluj',
    preview: 'Podgląd punktów',
  },
  player: {
    firstName: 'Imię',
    lastName: 'Nazwisko',
    email: 'Email',
    phone: 'Telefon',
    hcp: 'Handicap',
    upcomingMatches: 'Mecze do rozegrania',
    matchHistory: 'Historia meczów',
    noUpcoming: 'Brak meczów do rozegrania',
    noHistory: 'Brak rozegranych meczów',
    addPlayer: 'Dodaj zawodnika',
    editPlayer: 'Edytuj zawodnika',
  },
  group: {
    standings: 'Tabela',
    matches: 'Mecze',
  },
  admin: {
    addAdmin: 'Dodaj administratora',
    email: 'Email',
    password: 'Hasło',
    confirmDelete: 'Czy na pewno chcesz usunąć?',
  },
  season: {
    createSeason: 'Utwórz sezon',
    name: 'Nazwa',
    year: 'Rok',
  },
  round: {
    generate: 'Generuj grupy',
    approve: 'Zatwierdź',
    preview: 'Podgląd grup',
  },
  playoff: {
    title: 'Play-off',
    bracket: 'Drabinka',
    bracket116: 'Drabinka 1-16',
    bracket1732: 'Drabinka 17-32',
    bracket3348: 'Drabinka 33-48',
    holes18: '18 dołków',
    holes9: '9 dołków',
    holes918: '9/18 dołków',
    roundOf16: '1/8 Finału',
    quarterFinal: 'Ćwierćfinał',
    semiFinal: 'Półfinał',
    final: 'Finał',
    champion: 'Zwycięzca',
    tbd: 'Oczekuje na wynik',
    deadline: 'do',
    createPlayoff: 'Utwórz drabinki play-off',
    seedingPreview: 'Podgląd rozstawienia',
    confirmCreate: 'Zatwierdź i utwórz mecze',
    globalRanking: 'Ranking końcowy fazy grupowej',
    noPlayoff: 'Play-off nie został jeszcze utworzony.',
    playoffExists: 'Play-off już istnieje.',
    bye: 'BYE',
  },
  reminders: {
    send: 'Wyślij przypomnienia',
    sending: 'Wysyłanie...',
    sent: 'Wysłano',
    emailsSent: 'emaili wysłanych',
    noReminders: 'Brak przypomnień do wysłania (terminy nie wypadają za 7 lub 2 dni)',
    errors: 'błędów',
  },
  playerAuth: {
    loginWithPassword: 'Zaloguj hasłem',
    loginWithMagicLink: 'Zaloguj linkiem',
    email: 'Email',
    password: 'Hasło',
    login: 'Zaloguj',
    setPassword: 'Ustaw hasło',
    changePassword: 'Zmień hasło',
    newPassword: 'Nowe hasło',
    passwordMinLength: 'Minimum 6 znaków',
    passwordSet: 'Hasło zostało ustawione',
    invalidCredentials: 'Nieprawidłowy email lub hasło',
  },
  scoring: {
    config: 'Konfiguracja punktacji',
    bigPoints: 'Punktacja g\u0142\u00f3wna',
    smallPoints: 'Ma\u0142e punkty',
    win: 'Wygrana',
    draw: 'Remis',
    loss: 'Pora\u017cka',
    unplayed: 'Nierozegrany',
    walkoverWinner: 'Walkower (zwyci\u0119zca)',
    walkoverLoser: 'Walkower (przegrany)',
    winnerPoints: 'Wygrany',
    loserPoints: 'Przegrany',
    resultCode: 'Wynik',
    save: 'Zapisz konfiguracj\u0119',
    resetDefaults: 'Przywr\u00f3\u0107 domy\u015blne',
    saved: 'Konfiguracja zapisana',
  },
  common: {
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    edit: 'Edytuj',
    add: 'Dodaj',
    search: 'Szukaj...',
    loading: 'Ładowanie...',
    noData: 'Brak danych',
    back: 'Wróć',
  },
} as const
